# Generated by Django 5.1.6 on 2025-02-24 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_str', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HandWritten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('image', models.BinaryField(null=True)),
                ('result', models.TextField()),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyHandWritten_app.judge')),
            ],
        ),
    ]
